[package]
name = "kvs"
version = "0.1.0"
authors = ["Ban Nguy <ban.nguy@tutanota.com>"]
edition = "2024"

[dependencies]
assert_cmd = "2.0.17"
clap = { version = "4.5.39", features = ["derive"] }
predicates = "3.1.3"
serde_json = "1.0.140"
thiserror = "2.0.12"
tempfile = "3.20.0"
walkdir = "2.5.0"
